"""Initial migration

Revision ID: c08a54d763f9
Revises: 
Create Date: 2025-07-01 11:03:41.451150

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c08a54d763f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('agent_id', sa.String(length=50), nullable=False),
    sa.Column('employee_id', sa.String(length=50), nullable=True),
    sa.Column('license_number', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('hire_date', sa.DateTime(), nullable=False),
    sa.Column('department', sa.String(length=100), nullable=True),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.Column('manager_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('agent_type', sa.String(length=20), nullable=False),
    sa.Column('total_policies', sa.Integer(), nullable=True),
    sa.Column('active_policies', sa.Integer(), nullable=True),
    sa.Column('total_premium_written', sa.Float(), nullable=True),
    sa.Column('commission_rate', sa.Float(), nullable=True),
    sa.Column('total_commission_earned', sa.Float(), nullable=True),
    sa.Column('last_commission_date', sa.DateTime(), nullable=True),
    sa.Column('territory', sa.String(length=100), nullable=True),
    sa.Column('specialization', sa.String(length=100), nullable=True),
    sa.Column('license_state', sa.String(length=2), nullable=True),
    sa.Column('license_expiry', sa.DateTime(), nullable=True),
    sa.Column('certifications', sa.Text(), nullable=True),
    sa.Column('customer_satisfaction_score', sa.Float(), nullable=True),
    sa.Column('performance_rating', sa.String(length=10), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('is_top_performer', sa.Boolean(), nullable=True),
    sa.Column('can_approve_claims', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_agents_agent_id'), 'agents', ['agent_id'], unique=True)
    op.create_index(op.f('ix_agents_email'), 'agents', ['email'], unique=False)
    op.create_index(op.f('ix_agents_employee_id'), 'agents', ['employee_id'], unique=True)
    op.create_index(op.f('ix_agents_id'), 'agents', ['id'], unique=False)
    op.create_index(op.f('ix_agents_license_number'), 'agents', ['license_number'], unique=True)
    op.create_index(op.f('ix_agents_manager_id'), 'agents', ['manager_id'], unique=False)
    op.create_index(op.f('ix_agents_status'), 'agents', ['status'], unique=False)
    op.create_index(op.f('ix_agents_uuid'), 'agents', ['uuid'], unique=True)
    op.create_table('audit_logs',
    sa.Column('log_id', sa.String(length=50), nullable=False),
    sa.Column('session_id', sa.String(length=100), nullable=True),
    sa.Column('user_id', sa.String(length=50), nullable=True),
    sa.Column('user_email', sa.String(length=100), nullable=True),
    sa.Column('user_role', sa.String(length=50), nullable=True),
    sa.Column('action', sa.String(length=100), nullable=False),
    sa.Column('resource_type', sa.String(length=50), nullable=False),
    sa.Column('resource_id', sa.String(length=50), nullable=True),
    sa.Column('event_timestamp', sa.DateTime(), nullable=False),
    sa.Column('event_type', sa.String(length=50), nullable=False),
    sa.Column('severity', sa.String(length=10), nullable=True),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=500), nullable=True),
    sa.Column('request_method', sa.String(length=10), nullable=True),
    sa.Column('request_url', sa.String(length=500), nullable=True),
    sa.Column('old_values', sa.JSON(), nullable=True),
    sa.Column('new_values', sa.JSON(), nullable=True),
    sa.Column('changes', sa.JSON(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('stack_trace', sa.Text(), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=True),
    sa.Column('is_sensitive', sa.Boolean(), nullable=True),
    sa.Column('requires_review', sa.Boolean(), nullable=True),
    sa.Column('correlation_id', sa.String(length=100), nullable=True),
    sa.Column('parent_log_id', sa.String(length=50), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_event_timestamp'), 'audit_logs', ['event_timestamp'], unique=False)
    op.create_index(op.f('ix_audit_logs_id'), 'audit_logs', ['id'], unique=False)
    op.create_index(op.f('ix_audit_logs_log_id'), 'audit_logs', ['log_id'], unique=True)
    op.create_index(op.f('ix_audit_logs_parent_log_id'), 'audit_logs', ['parent_log_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_type'), 'audit_logs', ['resource_type'], unique=False)
    op.create_index(op.f('ix_audit_logs_session_id'), 'audit_logs', ['session_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_user_id'), 'audit_logs', ['user_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_uuid'), 'audit_logs', ['uuid'], unique=True)
    op.create_table('claims',
    sa.Column('claim_number', sa.String(length=50), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('claim_type', sa.String(length=50), nullable=False),
    sa.Column('claim_amount', sa.Float(), nullable=False),
    sa.Column('approved_amount', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('incident_date', sa.DateTime(), nullable=False),
    sa.Column('claim_date', sa.DateTime(), nullable=False),
    sa.Column('processed_date', sa.DateTime(), nullable=True),
    sa.Column('settlement_date', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('priority', sa.String(length=10), nullable=True),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('incident_location', sa.String(length=500), nullable=True),
    sa.Column('adjuster_id', sa.String(length=50), nullable=True),
    sa.Column('adjuster_name', sa.String(length=200), nullable=True),
    sa.Column('adjuster_notes', sa.Text(), nullable=True),
    sa.Column('settlement_method', sa.String(length=50), nullable=True),
    sa.Column('settlement_reference', sa.String(length=100), nullable=True),
    sa.Column('is_fraudulent', sa.Boolean(), nullable=True),
    sa.Column('requires_investigation', sa.Boolean(), nullable=True),
    sa.Column('has_attachments', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_claims_agent_id'), 'claims', ['agent_id'], unique=False)
    op.create_index(op.f('ix_claims_claim_number'), 'claims', ['claim_number'], unique=True)
    op.create_index(op.f('ix_claims_claim_type'), 'claims', ['claim_type'], unique=False)
    op.create_index(op.f('ix_claims_customer_id'), 'claims', ['customer_id'], unique=False)
    op.create_index(op.f('ix_claims_id'), 'claims', ['id'], unique=False)
    op.create_index(op.f('ix_claims_policy_number'), 'claims', ['policy_number'], unique=False)
    op.create_index(op.f('ix_claims_status'), 'claims', ['status'], unique=False)
    op.create_index(op.f('ix_claims_uuid'), 'claims', ['uuid'], unique=True)
    op.create_table('customers',
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('customer_number', sa.String(length=50), nullable=True),
    sa.Column('first_name', sa.String(length=100), nullable=False),
    sa.Column('last_name', sa.String(length=100), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('date_of_birth', sa.DateTime(), nullable=True),
    sa.Column('gender', sa.String(length=10), nullable=True),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('phone', sa.String(length=20), nullable=True),
    sa.Column('mobile', sa.String(length=20), nullable=True),
    sa.Column('address_line1', sa.String(length=200), nullable=True),
    sa.Column('address_line2', sa.String(length=200), nullable=True),
    sa.Column('city', sa.String(length=100), nullable=True),
    sa.Column('state', sa.String(length=50), nullable=True),
    sa.Column('postal_code', sa.String(length=20), nullable=True),
    sa.Column('country', sa.String(length=50), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('customer_type', sa.String(length=20), nullable=True),
    sa.Column('primary_agent_id', sa.String(length=50), nullable=True),
    sa.Column('registration_date', sa.DateTime(), nullable=False),
    sa.Column('last_contact_date', sa.DateTime(), nullable=True),
    sa.Column('preferred_contact_method', sa.String(length=20), nullable=True),
    sa.Column('credit_score', sa.Integer(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=True),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('marketing_consent', sa.Boolean(), nullable=True),
    sa.Column('is_vip', sa.Boolean(), nullable=True),
    sa.Column('has_claims', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_customers_customer_id'), 'customers', ['customer_id'], unique=True)
    op.create_index(op.f('ix_customers_customer_number'), 'customers', ['customer_number'], unique=True)
    op.create_index(op.f('ix_customers_email'), 'customers', ['email'], unique=False)
    op.create_index(op.f('ix_customers_id'), 'customers', ['id'], unique=False)
    op.create_index(op.f('ix_customers_primary_agent_id'), 'customers', ['primary_agent_id'], unique=False)
    op.create_index(op.f('ix_customers_status'), 'customers', ['status'], unique=False)
    op.create_index(op.f('ix_customers_uuid'), 'customers', ['uuid'], unique=True)
    op.create_table('payments',
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('transaction_reference', sa.String(length=100), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('payment_status', sa.String(length=20), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('payment_date', sa.DateTime(), nullable=False),
    sa.Column('due_date', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('gateway_transaction_id', sa.String(length=100), nullable=True),
    sa.Column('gateway_response', sa.Text(), nullable=True),
    sa.Column('processing_fee', sa.Float(), nullable=True),
    sa.Column('is_recurring', sa.Boolean(), nullable=True),
    sa.Column('is_late_payment', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_payments_agent_id'), 'payments', ['agent_id'], unique=False)
    op.create_index(op.f('ix_payments_customer_id'), 'payments', ['customer_id'], unique=False)
    op.create_index(op.f('ix_payments_id'), 'payments', ['id'], unique=False)
    op.create_index(op.f('ix_payments_payment_id'), 'payments', ['payment_id'], unique=True)
    op.create_index(op.f('ix_payments_policy_number'), 'payments', ['policy_number'], unique=False)
    op.create_index(op.f('ix_payments_transaction_reference'), 'payments', ['transaction_reference'], unique=False)
    op.create_index(op.f('ix_payments_uuid'), 'payments', ['uuid'], unique=True)
    op.create_table('policies',
    sa.Column('policy_number', sa.String(length=50), nullable=False),
    sa.Column('policy_type', sa.String(length=50), nullable=False),
    sa.Column('premium_amount', sa.Float(), nullable=False),
    sa.Column('coverage_amount', sa.Float(), nullable=False),
    sa.Column('deductible', sa.Float(), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('effective_date', sa.DateTime(), nullable=False),
    sa.Column('expiration_date', sa.DateTime(), nullable=False),
    sa.Column('renewal_date', sa.DateTime(), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=False),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('agent_id', sa.String(length=50), nullable=True),
    sa.Column('agent_name', sa.String(length=200), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('payment_frequency', sa.String(length=20), nullable=False),
    sa.Column('next_payment_due', sa.DateTime(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('terms_conditions', sa.Text(), nullable=True),
    sa.Column('auto_renewal', sa.Boolean(), nullable=True),
    sa.Column('is_group_policy', sa.Boolean(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_policies_agent_id'), 'policies', ['agent_id'], unique=False)
    op.create_index(op.f('ix_policies_customer_id'), 'policies', ['customer_id'], unique=False)
    op.create_index(op.f('ix_policies_id'), 'policies', ['id'], unique=False)
    op.create_index(op.f('ix_policies_policy_number'), 'policies', ['policy_number'], unique=True)
    op.create_index(op.f('ix_policies_policy_type'), 'policies', ['policy_type'], unique=False)
    op.create_index(op.f('ix_policies_status'), 'policies', ['status'], unique=False)
    op.create_index(op.f('ix_policies_uuid'), 'policies', ['uuid'], unique=True)
    op.create_table('receipts',
    sa.Column('receipt_number', sa.String(length=50), nullable=False),
    sa.Column('payment_id', sa.String(length=50), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('receipt_date', sa.DateTime(), nullable=False),
    sa.Column('policy_number', sa.String(length=50), nullable=True),
    sa.Column('customer_id', sa.String(length=50), nullable=True),
    sa.Column('customer_name', sa.String(length=200), nullable=False),
    sa.Column('customer_email', sa.String(length=100), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('payment_method', sa.String(length=50), nullable=False),
    sa.Column('receipt_status', sa.String(length=20), nullable=True),
    sa.Column('email_sent', sa.Boolean(), nullable=True),
    sa.Column('email_sent_at', sa.DateTime(), nullable=True),
    sa.Column('receipt_file_path', sa.String(length=500), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('uuid', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_receipts_customer_id'), 'receipts', ['customer_id'], unique=False)
    op.create_index(op.f('ix_receipts_id'), 'receipts', ['id'], unique=False)
    op.create_index(op.f('ix_receipts_payment_id'), 'receipts', ['payment_id'], unique=False)
    op.create_index(op.f('ix_receipts_policy_number'), 'receipts', ['policy_number'], unique=False)
    op.create_index(op.f('ix_receipts_receipt_number'), 'receipts', ['receipt_number'], unique=True)
    op.create_index(op.f('ix_receipts_uuid'), 'receipts', ['uuid'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_receipts_uuid'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_receipt_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_policy_number'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_payment_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_id'), table_name='receipts')
    op.drop_index(op.f('ix_receipts_customer_id'), table_name='receipts')
    op.drop_table('receipts')
    op.drop_index(op.f('ix_policies_uuid'), table_name='policies')
    op.drop_index(op.f('ix_policies_status'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_type'), table_name='policies')
    op.drop_index(op.f('ix_policies_policy_number'), table_name='policies')
    op.drop_index(op.f('ix_policies_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_customer_id'), table_name='policies')
    op.drop_index(op.f('ix_policies_agent_id'), table_name='policies')
    op.drop_table('policies')
    op.drop_index(op.f('ix_payments_uuid'), table_name='payments')
    op.drop_index(op.f('ix_payments_transaction_reference'), table_name='payments')
    op.drop_index(op.f('ix_payments_policy_number'), table_name='payments')
    op.drop_index(op.f('ix_payments_payment_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_customer_id'), table_name='payments')
    op.drop_index(op.f('ix_payments_agent_id'), table_name='payments')
    op.drop_table('payments')
    op.drop_index(op.f('ix_customers_uuid'), table_name='customers')
    op.drop_index(op.f('ix_customers_status'), table_name='customers')
    op.drop_index(op.f('ix_customers_primary_agent_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_id'), table_name='customers')
    op.drop_index(op.f('ix_customers_email'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_number'), table_name='customers')
    op.drop_index(op.f('ix_customers_customer_id'), table_name='customers')
    op.drop_table('customers')
    op.drop_index(op.f('ix_claims_uuid'), table_name='claims')
    op.drop_index(op.f('ix_claims_status'), table_name='claims')
    op.drop_index(op.f('ix_claims_policy_number'), table_name='claims')
    op.drop_index(op.f('ix_claims_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_customer_id'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_type'), table_name='claims')
    op.drop_index(op.f('ix_claims_claim_number'), table_name='claims')
    op.drop_index(op.f('ix_claims_agent_id'), table_name='claims')
    op.drop_table('claims')
    op.drop_index(op.f('ix_audit_logs_uuid'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_user_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_session_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_type'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_parent_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_log_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_event_timestamp'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_index(op.f('ix_agents_uuid'), table_name='agents')
    op.drop_index(op.f('ix_agents_status'), table_name='agents')
    op.drop_index(op.f('ix_agents_manager_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_license_number'), table_name='agents')
    op.drop_index(op.f('ix_agents_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_employee_id'), table_name='agents')
    op.drop_index(op.f('ix_agents_email'), table_name='agents')
    op.drop_index(op.f('ix_agents_agent_id'), table_name='agents')
    op.drop_table('agents')
    # ### end Alembic commands ###
